### ISSUE TITLE
error in droplet ubuntu 20 python3 from scratch

### ISSUE THREAD

**Issue by johnfelipe** [ajitsingh98/cattle-breed-classifier-webapp#1]
apt update
    apt upgrade
    shutdown -r now
    
    apt install python3-pip
    git clone https://github.com/ajitsingh98/cattle-breed-classifier-webapp.git
    cd cattle-breed-classifier-webapp
    pip install -r requirements.txt
show me this

    root@3-ubuntu-s-8vcpu-16gb-nyc1-01:~/cattle-breed-classifier-webapp# pip install -r requirements.txt
    ERROR: torch-1.6.0+cpu-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform.

how solve?

**Comment by ajitsingh98** [comment]
I don't have much idea about this as I don't use Linux but you can try this [link](https://forums.fast.ai/t/deploying-in-heroku-error-not-a-supported-wheel-on-this-platform/76196)

**Comment by johnfelipe** [comment]
wget https://download.pytorch.org/whl/cpu/torch-1.6.0%2Bcpu-cp37-cp37m-linux_x86_64.whl
    pip install torch-1.6.0+cpu-cp37-cp37m-linux_x86_64.whl

and delete torch of req file
Tnks
